[package]
name = "img-catechesis"
version = "0.1.0"
authors = ["Ben Schinn <schinn.ben@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
serde_json = "1.0"
color-convert = "0.1.0"
